// 从 Worker 再导出 API endpoint 常量；纯字符串字面量，tree-shake 安全。
export {
  ROUTE_MINI_APP_API_LIST,
  ROUTE_MINI_APP_API_MAIL,
  ROUTE_MINI_APP_API_MARK_ALL_READ,
  ROUTE_MINI_APP_API_TRASH_ALL_JUNK,
  ROUTE_REMINDERS_API,
  ROUTE_REMINDERS_API_EMAIL_CONTEXT,
  ROUTE_REMINDERS_API_ITEM,
  ROUTE_REMINDERS_API_RESOLVE_CONTEXT,
} from "@worker/handlers/hono/routes";
